### ISSUE TITLE
Can you atleast describe what it does that other plugin can't.

### ISSUE THREAD

**Issue by shahid777-py** [lervag/vim-rmarkdown#1]
can it do checkbox keybind just like in vimwiki for md

**Comment by lervag** [comment]
Hmm. Well, I don't remember. I created it 3 years ago, but then I never really used r markdown. So I think it is probably best to use another plugin.

**Comment by shahid777-py** [comment]
🤣🤣🤣🤣🤣🤣.....

**Comment by lervag** [comment]
Sorry about that. I should probably archive this repo... :p

**Comment by shahid777-py** [comment]
> Sorry about that. I should probably archive this repo... :p

u definatly should , by the way do u know any way to get checkbox in rmd like in vimwiki

**Comment by lervag** [comment]
No, sorry. I don't use vimwiki. :\
